### ISSUE TITLE
Room returns players: -1

### ISSUE THREAD

**Issue by Thioby** [morko/haxroomie#68]
When new room is created command `rooms` does return:
`ID: priv2 Status: running Players: -1/20`

This broke plugins like always-one-admin.

**Comment by Thioby** [comment]
@morko

**Comment by saviola777** [comment]
Which version of haxroomie are you using? can you post your config (at least the repositories part) so we can see which version of the plugin repositories you are using?

**Comment by morko** [comment]
Thanks for the report. Are you maybe using the GitHub version since I just realized the official release was broken due to changes in the core plugin repository. Hopefully the npm version should now be fixed (1.0.0 branch). 

If you are using the master branch of this GitHub repository it might break from time to time.

**Comment by morko** [comment]
Ok I see what happened now. You have run your room with the `noPlayer: true` option which was not yet supported. I've added support for that in the master branch and release is coming soonish.
